[colors.cursor]
cursor = "0x93a1a1"
text = "0x002b36"


[colors.primary]
background = "#09090F"
foreground = '#c7b198'

# Normal colors
[colors.normal]
black   = '#11111b'
red     = '#f38ba8'
green   = '#a6e3a1'
yellow  = '#f9e2af'
blue    = '#89b4fa'
magenta = '#cba6f7'
cyan    = '#74c7ec'
white   = '#cdd6f4'

# Bright colors (same as normal colors)
[colors.bright]
black   = '#11111b'
red     = '#f38ba8'
green   = '#a6e3a1'
yellow  = '#f9e2af'
blue    = '#89b4fa'
magenta = '#cba6f7'
cyan    = '#74c7ec'
white   = '#cdd6f4'


[env]
TERM = "xterm-256color"

[font]
size = 15.5

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window]
opacity = 1
dynamic_padding = false

[window.padding]
x = 30
y = 30

[cursor]
style = { blinking = "On" }
